auth/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import logout
from auth import views

urlpatterns = patterns('',
    url(r'^login/$', views.login,  name='login'),
    url(r'^logged_in/', views.logged_in,  name='logged_in'),
    url(r'^logout/', logout, 
        {'template_name': 'auth/logged_out.html'}, 
        name='logout'),
)

gcal_dedup/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import logout
import pick_calendar.views

urlpatterns = patterns('',
    url(r'^', include('pick_calendar.urls', 
                                    namespace='pick_calendar')),
    url(r'^accounts/', include('gcal_auth.urls', 
                                    namespace='gcal_auth')),
)

pick_calendar/urls.py
from django.conf.urls import patterns, url
from pick_calendar import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^calendars/(?P<target>\w+)/$', views.calendars, name='calendars'),
    url(r'^calendars/(?P<target>\w+)/selected/$', views.calendars_selected,  
        name='calendars_selected'),
    url(r'^deduplify/$', views.deduplify, name='deduplify'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^settings/update/$', views.settings_update, name='settings_update'),
    url(r'^settings/default/$', views.settings_update, 
        {'default': True},
        name='settings_default'),
)

pick_calendar/models.py
from django.db import models
from django.contrib.auth.models import User
from oauth2client.django_orm import CredentialsField


class CredentialsModel(models.Model):
  id = models.ForeignKey(User, primary_key=True)
  credential = CredentialsField()

pick_calendar/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.utils.html import escape
import json
from oauth2client.django_orm import Storage
from gcal_api.google_calendar_dups import GCalMover
from gcal_auth.models import CredentialsModel
from django.contrib.auth.decorators import login_required


def index(request):
    #TODO: move out of pick_calendar, and into main site
    #from pudb import set_trace; set_trace()
    progress = get_progress(request)
    context = {'progress': progress,}
    return render(request, 'pick_calendar/index.html', context)

def reset(request):
    progress = get_progress(request, reset=True)
    return redirect('pick_calendar:index')

def get_progress(request, reset=False):
    progress = request.session.get('progress')
    if not progress or reset:
        progress = {'source': [],
                    'destination': [],
                    'completed': None,
                    'dryrun': False,
                    'replace_text': False,
                    'select_original': 'created_earliest',
                    'created_earliest': True,
                    'updated_earliest': False,
                    'min_chars': False,
                    'ignore_attrs_num': False,
                    'size_diff_threshold': 85,
                    'ascending': True,
                    'descending': False,
                    'rep1f': '',
                    'rep1r': '',
                    }
        request.session['progress'] = progress
    return progress

@login_required
def calendars(request, target):
    #DONE: handle when user is not logged in 
    user = request.user 
    storage = Storage(CredentialsModel, 'id', user, 'credential')
    creds = storage.get()
    gcm = GCalMover(creds)
    calendars = gcm.get_calendars()
    progress = get_progress(request)
    progress['calendar_list'] = calendars
    request.session['progress'] = progress
    #from pudb import set_trace; set_trace()
    question = 'Select {} calendar'.format(target)
    if target == 'source':
        form_type = 'checkbox'
        question = '{}(s)'.format(question)
    elif target == 'destination':
        form_type = 'radio'
    context = {'choice_list': calendars,
               'question': question,
               'error_message': '',
               'form_type': form_type,
               'form_url': reverse('pick_calendar:calendars_selected', 
                                   args=(target,))}
    return render(request, 'pick_calendar/calendars.html', context)

def get_selected(request, progress):
    calendar_idxs = request.POST.getlist('choice')
    calendar_idxs = [int(i) for i in calendar_idxs]
    calendar_list = progress.get('calendar_list')
    calendars_selected = [calendar_list[i] for i in calendar_idxs]
    return calendars_selected

def calendars_selected(request, target):
    #from pudb import set_trace; set_trace()
    progress = get_progress(request)
    calendars_selected = get_selected(request, progress)
    progress[target] = calendars_selected
    if progress['destination']:
        progress['completed'] = 'destination'
    else:
        progress['completed'] = target
    request.session['progress'] = progress
    return redirect('pick_calendar:index')
    #return redirect('pick_calendar:index')
    #return redirect('{}#source'.format(reverse('index')))

def deduplify(request):
    #from pudb import set_trace; set_trace()
    progress = get_progress(request)
    source = progress.get('source')
    destination = progress.get('destination')[0]
    user = request.user 
    storage = Storage(CredentialsModel, 'id', user, 'credential')
    creds = storage.get()
    sort_method, ascending = _get_sort_method(request)
    ascending = progress['ascending']
    ignore_attrs_num = progress['ignore_attrs_num']
    size_diff_threshold = float(progress['size_diff_threshold']) / 100.0
    gcm = GCalMover(creds)
    log = gcm.deduplify(source, destination, 
                        sort_method=sort_method,
                        ascending=ascending,
                        ignore_attrs_num=ignore_attrs_num,
                        size_diff_threshold=size_diff_threshold,
                        dry_run=progress['dryrun'],
                        std_out=False,
                        )
    #from pudb import set_trace; set_trace()
    progress['log'] = log
    progress['completed'] = True if not progress['dryrun'] else 'dryrun'
    request.session['progress'] = progress
    return redirect('pick_calendar:index')

def _get_sort_method(request):
    progress = get_progress(request)
    if progress.get('created_earliest') == True:
        sort_method = 'created'
    elif progress.get('updated_earliest') == True:
        sort_method = 'updated'
    elif progress.get('min_chars') == True:
        sort_method = 'textlen'
    else:
        sort_method = 'created'
    if progress.get('descending') == True:
        ascending = False
    else:
        ascending = True
    return sort_method, ascending


def settings(request):
    #from pudb import set_trace; set_trace()
    progress = get_progress(request)
    dryrun = progress['dryrun']
    select_original = progress['select_original']
    replace_text = progress['replace_text']
    rep1f = escape(progress['rep1f'])
    rep1r = escape(progress['rep1r'])
    context = {'dryrun': dryrun,
               'replace_text': replace_text,
               'select_original': select_original,
               'rep1f': rep1f,
               'rep1r': rep1r,
               'created_earliest': progress['created_earliest'],
               'updated_earliest': progress['updated_earliest'],
               'min_chars': progress['min_chars'],
               'ignore_attrs_num': progress['ignore_attrs_num'],
               'size_diff_threshold': progress['size_diff_threshold'],
               'ascending': progress['ascending'],
               'descending': progress['descending'],
              }
    context_json = json.dumps(context)
    return render(request, 'pick_calendar/settings.html', {'context': context_json})

def settings_update(request, default=False):
    #from pudb import set_trace; set_trace()
    progress = get_progress(request)
    old_dryrun = progress.get('dryrun')
    dryrun = request.POST.get('dryrun') is not None

    # when user runs dryrun then switches off dryrun, we clear log
    # this ensures the log doesn't reappear by simply re-enabling dryrun
    # immediately after that
    if ( old_dryrun and not dryrun 
         and progress['completed'] == 'dryrun' ):
        if progress['source'] and progress['destination']:
            progress['completed'] = 'destination'
        elif progress['source']:
            progress['completed'] = 'source'
        else:
            progress['completed'] = None

    # replace_text not currently implemented
    #replace_text = request.POST.get('replace_text') is not None
    #rep1f = request.POST.get('rep1f')
    #rep1r = request.POST.get('rep1r')
    #progress['replace_text'] = replace_text
    #progress['rep1f'] = rep1f 
    #progress['rep1r'] = rep1r

    ascending = request.POST.get('ascending')
    #if ascending is not False:
        #ascending = True;

    if default:
        progress['dryrun'] = False
        progress['created_earliest'] = True
        progress['updated_earliest'] = False
        progress['min_chars'] = False
        progress['select_original'] = 'created_earliest'
        progress['ignore_attrs_num'] = False
        progress['ascending'] = True
        progress['descending'] = False
        progress['size_diff_threshold'] = 85;
        request.session['progress'] = progress
        return redirect('pick_calendar:settings')
    else:
        progress['dryrun'] = dryrun
        select_original = request.POST.get('select_original')
        progress['select_original'] = select_original
        progress['created_earliest'] = select_original == 'created_earliest'
        progress['updated_earliest'] = select_original == 'updated_earliest'
        progress['min_chars'] = select_original == 'min_chars'
        progress['ignore_attrs_num'] = request.POST.get('ignore_attrs_num') is not None
        progress['ascending'] = ascending == 'ascending'
        progress['descending'] = ascending == 'descending'
        progress['size_diff_threshold'] = request.POST.get('size_diff_threshold')
        request.session['progress'] = progress
        return redirect('pick_calendar:index')

pick_calendar/templates/pick_calendar/base.html
<div style="float:left;">
    <a href="{%url 'pick_calendar:index' %}">gcal_dedup</a>
</div>

<div style="float:right;">
    {% if user.username %}
        <div>
            {{ user.username }}
        </div>
        <div>
            <a href="{%url 'pick_calendar:logout' %}">logout</a>
        </div>
    {% else %}
        <div>
            <a href="{%url 'pick_calendar:auth' %}">login</a>
        </div>
    {% endif %}
</div>

<div style="clear:both;"></div>
<hr>

<div id="content">
    {% block content %}{% endblock %}
</div>

pick_calendar/templates/pick_calendar/calendars.html
{% extends "base.html" %}

{% block content %}

  <!--Source Calendar(s) -->
  <div id="source_calendars" class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">{{ question }}</h3>
      </div>
      <div class="source panel-body">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        {% if choice_list %}
            <form action="{{ form_url }}" method="post">
            {% csrf_token %}
            {% for choice in choice_list %}
            <input type="{{ form_type  }}" name="choice" id="choice{{ forloop.counter }}" value="{{ forloop.counter0 }}" />
                <label for="choice{{ forloop.counter }}">{{ choice.summary }}</label><br />
            {% endfor %}
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="{% url 'pick_calendar:index'  %}">
              <button type="button" class="btn btn-default pull-right">Cancel</button>
            </a>
            </form>
        {% else %}
            <p>Error getting list of calendars</p>
        {% endif %}
    </div>
</div>

{% endblock %}

pick_calendar/templates/pick_calendar/calendars_selected.html
{% extends "base.html" %}

{% block content %}

<h1>Success</h1>

{% if calendar_list %}
    <ul>
    {% for calendar in calendar_list %}
        <li>{{ calendar }}</li>
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}

pick_calendar/templates/pick_calendar/index.html
{% extends "base.html" %}

  {% block content %}


  <!--Source Calendar(s) -->
  <div id="source" 
     {% if progress.source %}
       class="panel panel-default"
     {% else %}
       class="panel panel-primary"
     {% endif %}
    >
      <div class="panel-heading">
        <h3 class="panel-title">Source Calendar(s)</h3>
      </div>
      <div class="source panel-body">
      {% if progress.source %}
          <ul>
              {% for source in progress.source %}
                  <li>{{ source.summary }}</li>
              {% endfor %}
          </ul>
              <a class='btn btn-default' href="{%url 'pick_calendar:calendars' 'source' %}">
                  Reset source calendar(s)
              </a>
      {% else %}
              <a class='btn btn-primary' href="{%url 'pick_calendar:calendars' 'source' %}">
                  Select
              </a>
      {% endif %}
      </div>
  </div>


  <!--Destination Calendar-->
  <div id="destination" 
     {% if not progress.source or progress.destination %}
       class="panel panel-default"
     {% else %}
       class="panel panel-primary"
     {% endif %}
    >
      <div class="panel-heading">
        <h3 class="panel-title">Destination Calendar</h3>
      </div>
      <div class="destination panel-body">
      {% if progress.source %}
        {% if progress.destination %}
            <ul>
                {% for choice in progress.destination %}
                    <li>{{ choice.summary }}</li>
                {% endfor %}
            </ul>
                <a class='btn btn-default' href="{%url 'pick_calendar:calendars' 'destination' %}">
                    Reset destination calendar
                </a>
        {% else %}
                <a class='btn btn-primary' href="{%url 'pick_calendar:calendars' 'destination' %}">
                    Select
                </a>
        {% endif %}
    {% endif %}
      </div>
  </div>

<!--Deduplify link/button-->

<div id="padded-box">
{% if progress.completed == 'destination' or progress.completed == 'dryrun' %}
    <div id="deduplify">
            <a class='btn btn-danger btn-lg' id='deduplify-button'
                href="{%url 'pick_calendar:deduplify' %}">
                Deduplify
            </a>
    </div>

    <div id="spinner-div" class="spinner-div"
                          style="display:none;" >
      <div id="spinner" class="throbber-loader">
      </div>
    </div>
{% endif %}
</div>


<!--Log/results-->

<div id="log">
{% if progress.log %}
{% if progress.completed == True or progress.completed == 'dryrun' and progress.dryrun %}

    <div id="log-header">
        <h2>Log/Results:</h2>
    </div>

    <ol>
    {% for group in progress.log %}
        
        <li>{{ group.tests }}
            <ul>
                <li>Keep
                    <ul>
                        <li>
                            <span class="event-summary">
                                {{ group.keep.summary }}
                            </span><br>
                            <span class="event-date">
                                {{ group.keep.start_pretty }} - 
                                {{ group.keep.end_pretty }} <br>
                            </span>
                            <span class="event-description">
                                {{ group.keep.description }} <br>
                            </span>
                            <span class="event-location">
                                location: {{ group.keep.location }} <br>
                            </span>
                            <span class="event-created">
                                created: {{ group.keep.created }} <br>
                            </span>
                            <span class="event-updated">
                                updated: {{ group.keep.updated }} <br>
                            </span>
                            <span class="event-calendar">
                                calendar: {{ group.keep.organizer.displayName }}<br>
                            </span>
                        </li>
                    </ul>
                </li>
                <li>Move
                    <ul>
                        {% for g in group.remove %}
                            <li>
                                {% if g.moved_result == False %}
                                    <span class="moved-result">
                                        MOVE FAILED (event could not be moved)<br>
                                    </span>
                                {% endif %}
                                <span class="event-summary">
                                    {{ g.event.summary }}
                                </span><br>
                                <span class="event-date">
                                    {{ g.event.start_pretty }} - 
                                    {{ g.event.end_pretty }} <br>
                                </span>
                                <span class="event-description">
                                    {{ g.event.description }} <br>
                                </span>
                                <span class="event-location">
                                    location: {{ g.event.location }} <br>
                                </span>
                                <span class="event-created">
                                    created: {{ g.event.created }} <br>
                                </span>
                                <span class="event-updated">
                                    updated: {{ g.event.updated }} <br>
                                </span>
                                <span class="event-calendar">
                                    calendar: {{ g.event.organizer.displayName }}<br>
                                </span>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </li>
    {% endfor %}
    </ol>

{% endif %}
{% endif %}
</div>


{% endblock %}


{% block js %}{{ block.super }}
<script type="text/javascript">
$(document).ready(function(){
    $('#deduplify-button').click(function() {
        $('#spinner-div').show();
    });
});
</script>
{% endblock %}

pick_calendar/templates/pick_calendar/logged_out.html
{% extends "pick_calendar/base.html" %}

{% block content %}
<h3>Logged out.</h3>
{% endblock %}

pick_calendar/templates/pick_calendar/picked.html
<h1>Success</h1>

{% if calendar_list %}
    <ul>
    {% for calendar in calendar_list %}
        <li>{{ calendar }}</li>
    {% endfor %}
    </ul>
{% endif %}

pick_calendar/templates/pick_calendar/select_calendar.html
{% extends "pick_calendar/base.html" %}

{% block content %}

<h1>{{ question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if choice_list %}
    <form action="{{ form_url }}" method="post">
    {% csrf_token %}
    {% for choice in choice_list %}
        <input type="checkbox" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.summary }}</label><br />
    {% endfor %}
    <input type="submit" value="Submit" />
    </form>
{% else %}
    <p>Error getting list of calendars</p>
{% endif %}

{% endblock %}

pick_calendar/templates/pick_calendar/select_calendar_result.html
{% extends "pick_calendar/base.html" %}

{% block content %}

<h1>Success</h1>

{% if calendar_list %}
    <ul>
    {% for calendar in calendar_list %}
        <li>{{ calendar }}</li>
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}

pick_calendar/templates/pick_calendar/select_calendars.html
{% extends "base.html" %}

{% block content %}

<h1>Success</h1>

{% if calendar_list %}
    <ul>
    {% for calendar in calendar_list %}
        <li>{{ calendar }}</li>
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}

pick_calendar/templates/pick_calendar/settings.html
{% extends "base.html" %}

{% block content %}

  <div class="panel panel-primary settings">
    <div class="panel-heading">
      <h3 class="panel-title">Settings</h3>
    </div>

    <div class="panel-body">

      <form action="{% url 'pick_calendar:settings_update' %}" method="post">
        {% csrf_token %}

        <!--<h5 class="list-group-heading">Dry Run</h3>-->
        <!--<label>Options-->
        <!--</label>-->

        <div class="form-group">
            <div class="checkbox">
              <label>
                <input type="checkbox" 
                       id="dryrun" 
                       name='dryrun' 
                       value="True">
                Dry Run  (just show report of what would happen.  Don't actually move anything.
              </label>
            </div>
        </div>

        <div class="form-group">
            <!--<label>Tests (to avoid false positives, etc)</label>-->

            <div class="checkbox">
              <label>
                <input type="checkbox" 
                       id="ignore_attrs_num" 
                       name='ignore_attrs_num' 
                       value="True">
                Ignore number of fields/attributes
              </label>
            </div>


            <label for="size_diff_threshold">Size difference threshold</label>
            <input type="number" 
                   class="form-control" 
                   id="size_diff_threshold" 
                   name="size_diff_threshold"
                   placeholder="85">

        </div>






        <!--<hr />-->


        <div class="form-group">

            <!--<h5 class="list-group-heading">Select original event by:</h5>-->
            <label>Select Original Event By:</label>

            <div class="radio">
              <label>
                <input type="radio" 
                       name="select_original" 
                       id="created_earliest" 
                       value="created_earliest"
                       checked >
                Date/Time Created
              </label>
            </div>

            <div class="radio">
              <label>
                <input type="radio" 
                       name="select_original" 
                       id="updated_earliest" 
                       value="updated_earliest" >
                Date/Time Updated
              </label>
            </div>

            <div class="radio">
              <label>
                <input type="radio" 
                       name="select_original" 
                       id="min_chars" 
                       value="min_chars" >
                Combined Text-Length
              </label>
            </div>
        </div> <!--form-group-->

        <div class="form-group">
            <label>Select Original Event (Ascending/Descending)</label>

            <div class="radio">
              <label>
                <input type="radio" 
                       id="ascending" 
                       name='ascending' 
                       value="ascending"
                       checked >
                Ascending
              </label>
            </div>

            <div class="radio">
              <label>
                <input type="radio" 
                       id="descending" 
                       name='ascending' 
                       value="descending" >
                Descending
              </label>
            </div>
        </div> <!--form-group-->







        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'pick_calendar:settings_default' %}">
        <button type="button" 
                class="btn btn-default">Defaults</button>
        </a>
        <a href="{% url 'pick_calendar:index' %}">
        <button type="button" 
                class="btn btn-default pull-right">Cancel</button>
        </a>

      </form>
    </div> <!--panel-body-->
  </div> <!--panel-->

{% endblock content %}


{% block js %}{{ block.super }}
  {% load staticfiles %}
  <!--put context into global namespace so we can access in javascript-->
  <script type="text/javascript">
    var current_settings = {};
    current_settings.dryrun = {{ context|safe }}.dryrun;
    current_settings.created_earliest = {{ context|safe }}.created_earliest;
    current_settings.updated_earliest = {{ context|safe }}.updated_earliest;
    current_settings.min_chars = {{ context|safe }}.min_chars;
    current_settings.ignore_attrs_num = {{ context|safe }}.ignore_attrs_num;
    current_settings.ascending = {{ context|safe }}.ascending;
    current_settings.descending = {{ context|safe }}.descending;
    current_settings.size_diff_threshold = {{ context|safe }}.size_diff_threshold;
  </script>
  <!--restore current settings-->
  <script src="{% static 'settings.js' %}"></script> 
{% endblock js %}