auth/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import logout
from auth import views

urlpatterns = patterns('',
    url(r'^login/$', views.login,  name='login'),
    url(r'^logged_in/', views.logged_in,  name='logged_in'),
    url(r'^logout/', logout, 
        {'template_name': 'auth/logged_out.html'}, 
        name='logout'),
)

gcal_dedup/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import logout
import pick_calendar.views

urlpatterns = patterns('',
    url(r'^', include('pick_calendar.urls', 
                                    namespace='pick_calendar')),
    url(r'^accounts/', include('gcal_auth.urls', 
                                    namespace='gcal_auth')),
)

pick_calendar/urls.py
from django.conf.urls import patterns, url
from pick_calendar import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^calendars/(?P<target>\w+)/$', views.calendars, name='calendars'),
    url(r'^calendars/(?P<target>\w+)/selected/$', views.calendars_selected,  
        name='calendars_selected'),
    url(r'^deduplify/$', views.deduplify, name='deduplify'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^settings/update/$', views.settings_update, name='settings_update'),
    url(r'^settings/default/$', views.settings_update, 
        {'default': True},
        name='settings_default'),
)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% block head %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!--<meta name="description" content="">-->
    <!--<meta name="author" content="">-->
    <!--<link rel="icon" href="../../favicon.ico">-->
    <title>gcal_dedup</title>

    {% load staticfiles %}

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css"
       href="{% static 'bootstrap.min.css' %}" />

    <link rel="stylesheet" type="text/css"
       href="{% static 'bootstrap-theme.min.css' %}" />

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link rel="stylesheet" type="text/css"
       href="{% static 'ie10-viewport-bug-workaround.css' %}" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'throbber.css' %}" />

  </head>
  {% endblock head %}

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" 
                   class="navbar-toggle collapsed" 
                   data-toggle="collapse" 
                   data-target="#navbar" 
                   aria-expanded="false" 
                   aria-controls="navbar" >
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand" >
            gcal_dedup
          </span>
        </div> <!--navbar-header-->
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li 
              {% if request.path != '/settings/' %}
                class="active"
              {% endif %}
              >
              <a href="{% url 'pick_calendar:index' %}">Home</a>
            </li>
            <li> 
              <a href="{% url 'pick_calendar:reset' %}">Reset</a>
            </li>
            <li
              {% if request.path == '/settings/' %}
                class="active"
              {% endif %}
              >
              <a href="{% url 'pick_calendar:settings' %}">Settings</a>
            </li>
            <li id='scroll-top' style="display:none;">
              <a href="#">Top</a>
            </li>
            <!--<li class="dropdown">-->
              <!--<a href="#" -->
                  <!--class="dropdown-toggle" -->
                  <!--data-toggle="dropdown" -->
                  <!--role="button" -->
                  <!--aria-haspopup="true" -->
                  <!--aria-expanded="false">-->
                <!--Dropdown <span class="caret"></span>-->
              <!--</a>-->
              <!--<ul class="dropdown-menu">-->
                <!--<li><a href="#">Action</a></li>-->
                <!--<li><a href="#">Another action</a></li>-->
                <!--<li><a href="#">Something else here</a></li>-->
                <!--<li role="separator" class="divider"></li>-->
                <!--<li class="dropdown-header">Nav header</li>-->
                <!--<li><a href="#">Separated link</a></li>-->
                <!--<li><a href="#">One more separated link</a></li>-->
              <!--</ul>-->
            <!--</li> [>dropdown<]-->
          </ul> <!--navbar-nav-->
          <ul class="nav navbar-nav navbar-right">
            <!--<li class="active">-->
            {% if not user.username %}
              <li>
                <a href="{% url 'gcal_auth:login' %}">Login</a>
              </li>
            {% else %}
              <li>
                <a href="#">[{{ user.username }}]</a>
              </li>
              <li>
                <a href="{% url 'gcal_auth:logout' %}">Logout</a>
              </li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">

      <div id="content">
        {% block content %}{% endblock %}
      </div>

      <footer class="footer">
        <p>&copy; 2015</p>
      </footer>

    </div> <!-- /container -->


    {% block js %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script 
      src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
    </script>

    <!-- Include all compiled plugins (below), 
         or include individual files as needed -->
    <script src="{% static 'bootstrap.min.js' %}"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'ie10-viewport-bug-workaround.js' %}"></script>

    <!-- scroll to top button  -->
    <script src="{% static 'scrolltop.js' %}"></script>

    {% endblock js %}
  </body>
</html>